/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 highDubai.glb 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function HighDubai(props) {
	const { nodes, materials } = useGLTF("/HighDubai.glb");
	return (
		<group {...props} dispose={null} position={[0, 0, 0]}>
			<group rotation={[-Math.PI / 2, 0, 0]} scale={0.001}>
				<group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
					<group
						position={[3006994.25, 0, 443723]}
						rotation={[-Math.PI / 2, 0, -Math.PI / 4]}
						scale={100}
					>
						<mesh
							geometry={nodes.int01.geometry}
							material={materials.alone01}
							position={[0.001, -0.001, 0]}
						/>
						<mesh
							geometry={nodes.int02.geometry}
							material={materials.alone02}
							position={[0.001, -0.001, 0]}
						/>
						<mesh
							geometry={nodes.int03.geometry}
							material={materials.alone03}
							position={[0.001, -0.001, 0]}
						/>
						<mesh
							geometry={nodes.noInteraction.geometry}
							material={materials.noInteraction}
							position={[0.001, -0.001, 0]}
						/>
					</group>
				</group>
			</group>
		</group>
	);
}

useGLTF.preload("/HighDubai.glb");
